# 应用服务 WEB 访问端口
server:
  port: 7090
  servlet:
    context-path: /api
    session:
      timeout: PT60M

# Spring MVC配置
spring:
  redis:
    database: 0
    host: 192.168.15.100
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000
    password: redis
  servlet:
      multipart:
        max-file-size: 10240MB
        max-request-size: 10240MB
  mvc:
    favicon:
      enable: false
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://192.168.150.100:3306/witchPan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 5917876liu
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com
    port: 465
    username: 2729070152@qq.com
    password: aaluyciblgxadfha
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

# 项目目录 logger日志位置
# /witchcontains
project:
  folder: /store

# 日志级别配置
log:
  root:
    level: info

# 超级管理员邮箱
admin:
  emails: 2729070152@qq.com

# 是否是开发环境
dev: false

# QQ登录相关配置
qq:
  app:
    id: 12333   #id和key互联中心去找
    key: 2222222
  url:
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    access:
      token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    user:
      info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
    redirect: http://witchweb.konnoyuuki.fun/qqlogincalback  #这个是自己成功登陆后的回调地址